---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 19/04/23 16:57
---

require("media.lua.client.EnumModData")

---Read Weight From Hd
local function readWeightFromHd()
    local weight = readSingleValueIntoModData( EnumModData.WEIGHT )
    setWeight_PZ(weight)
end

---Read Calories From Hd
local function readCaloriesFromHd()
    local calories = readSingleValueIntoModData( EnumModData.CALORIES )
    setCalories_PZ(calories)
end

---Write Weight From Hd
local function writeWeightFromHd()
    insertSingleValueIntoModData(EnumModData.WEIGHT, getWeight_PZ())
end

---Write Calories From Hd
local function writeCaloriesFromHd()
    insertSingleValueIntoModData(EnumModData.CALORIES, getCalories_PZ())
end

---Create Character Nutrition
function createCharacterNutrition()
    readWeightFromHd()
    readCaloriesFromHd()
end

---Wwrite Character Nutrition
function writeCharacterNutrition()
    writeWeightFromHd()
    writeCaloriesFromHd()
end

