---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---
require("media.lua.client.EnumModData")

---Read Zombies Killed From Hd
---@return int
local function readZombieKillsFromHd(character)

    local zombieKills =
    readSingleValueIntoModData( EnumModData.ZOMBIE_KILLS)

    setZombieKills_PZ(character, zombieKills)
end

---Create Zombies Kills
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createZombieKills(character)
    readZombieKillsFromHd(character)
end

---Write Zombies Kills To Hd
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function writeZombieKillsToHd(character)
    insertSingleValueIntoModData(EnumModData.ZOMBIE_KILLS,
            getZombieKills_PZ(character) )
end