---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 13:52
---

local nameModData = "characterPerkDetails"

---Read Character Perk Details From Hd
---@return table string profession, PerkFactory.Perk perk, int level, float xp, boolean flag
local function readCharacterPerkDetailsFromHd()

    local characterPerkDetails =
    ModData.get(nameModData)

    local lines = {}
    characterTableX_DestroyTable()

    for _, v in pairs(characterPerkDetails) do
        for s in v:gmatch("[^\r-]+") do
            table.insert(lines, s)
        end

        --profession, perk, level, xp
        characterTableX_addPerkDetails(nil,
                getPerkFromName_PZ(lines[1]),
                tonumber(lines[2]),
                tonumber(lines[3]) + 0.0)

        lines = {}
    end

    return characterTableX_getPerkDetails()
end

---Delete  all skills Character
---@param character IsoGameCharacter
local function deleteCharacter(character)
    local characterAllSkills = {}
    characterAllSkills = getCharacterAllSkills(character)

    for _, v in pairs(characterAllSkills) do
        removePerkLevel(character, v.perk)
    end
end

---Copy Character Skill
---@param character IsoGameCharacter
function createCharacterSkill(character)
    local characterSkills = {}
    characterSkills = readCharacterPerkDetailsFromHd()

    deleteCharacter(character)

    for _, v in pairs(characterSkills) do
        setPerkLevel(character, v.perk, v.xp)
    end
end

---Write Character Perk Details To Hd
---@param character IsoGameCharacter
function writeCharacterPerkDetailsToHd(character)
    ModData.remove(nameModData)

    local lines = {}

    local characterAllSkills = {}
    characterAllSkills = getCharacterAllSkills(character)

    for i, v in pairs(characterAllSkills) do
        lines[i] = ( v.perk:getName() .. "-" ..
                tostring(v.level)  .. "-" ..
                tostring(v.xp) )

        ModData.add(nameModData, lines)
    end
end




