---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 13:52
---

require("media.lua.client.EnumModData")

---Read Character Perk Details From Hd
---@return table string profession, PerkFactory.Perk perk, int level, float xp, boolean flag
local function readCharacterPerkDetailsFromHd()

    local characterPerkDetails =
    ModData.get(EnumModData.CHARACTER_PERK_DETAILS )

    local lines = {}
    characterTableX_DestroyTable()

    for _, v in pairs(characterPerkDetails) do
        for s in v:gmatch("[^\r-]+") do
            table.insert(lines, s)
        end

        --profession, perk, level, xp
        characterTableX_addPerkDetails(nil,
                getPerkFromName_PZ(lines[1]),
                tonumber(lines[2]),
                tonumber(lines[3]) + 0.0)

        lines = {}
    end

    -- andrebbe inserito nel oggetto ( se ci fosse )
    -- lines[1] = ModData.get(EnumModData.PROFESSION )
    return characterTableX_getPerkDetails()
end

---Delete  all skills Character
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local function deleteCharacter(character)
    local characterAllSkills = {}
    characterAllSkills = getCharacterAllSkills(character)

    for _, v in pairs(characterAllSkills) do
        removePerkLevel(character, v.perk)
    end

    setCharacterProfession_PZ("")
end

---Copy Character Skill
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function createCharacterSkill(character)
    local characterSkills = {}
    characterSkills = readCharacterPerkDetailsFromHd()

    deleteCharacter(character)

    for _, v in pairs(characterSkills) do
        setPerkLevel(character, v.perk, v.xp)
    end
    setCharacterProfession_PZ(EnumModData.PROFESSION)
end

---Write Character Perk Details To Hd
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function writeCharacterPerkDetailsToHd(character)
    ModData.remove(EnumModData.CHARACTER_PERK_DETAILS )

    local lines = {}

    local characterAllSkills = {}
    characterAllSkills = getCharacterAllSkills(character)

    for i, v in pairs(characterAllSkills) do
        lines[i] = ( v.perk:getName() .. "-" ..
                tostring(v.level)  .. "-" ..
                tostring(v.xp) )

        ModData.add(EnumModData.CHARACTER_PERK_DETAILS, lines)
    end


    lines = {}
    table.insert(lines, EnumModData.PROFESSION )

    ModData.add(EnumModData.PROFESSION, lines)
end




