---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

local nameModData = "characterLifeTime"
local date_ = { day, month, year}

local function addDate(day, month, year)
    table.insert(date_, {
        day = day,
        month = month,
        year = year
    })
end

---Read Life Time From Hd
function readLifeTimeFromHd()
    local lines = {}

    lines = ModData.get(nameModData)

    print("readLifeTimeFromHd()")
    for i, v in pairs(lines) do
        print(tostring(v.day) .. " " .. tostring(v.month))
    end

    return lines[1]
end

---Set Life Time
---@param day int
---@param month int
---@param year int ( disabilited )
function setLifeTime(day, month, year)

    GameTime():setStartMonth(3)

    --GameTime():setDay(1)
    --GameTime():setMonth(2)
    -- GameTime():setYear(year)
end

---Get Life Time
---@param character IsoGameCharacter
function getLifeTime(character)
    return getGameTime():getTimeSurvived(character)
end

---Create Life Time
---@param character IsoGameCharacter
function createLifeTime(character)
    local lifeTime = readLifeTimeFromHd()
    setLifeTime(character, lifeTime)
end

---Write Life Time To Hd
---@param character IsoGameCharacter
function writeLifeTimeToHd(character)
    ModData.remove(nameModData)

    local lifeTime = getLifeTime(character)

    local lines = {}
    for s in lifeTime:gmatch("[%d]+") do
        table.insert(lines, s)
    end

    for _, v in pairs(lines) do
        addDate(lines[1] , lines[2], nil)
    end

    ModData.add(nameModData, date_)
end