---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 02/05/23 15:38
---

require("media.lua.shared.DbgLeleLib")

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    key34(character, key)
    key35(character, key)
    key36(character, key)
end

-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > get profession \n")
        --character:getSurname() ..
        --        " " .. character:getName()
        -- print(character:getSurname() .. " " .. character:getName())
        -- print(character:getUsername())
        print(character:getDisplayName())

    end
end

---@param character IsoGameCharacter
function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h > set profession \n")
        readBook(character)
    end
end

---@param character IsoGameCharacter
function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j > delete \n")
        -- removeMoData()
        -- setZombieKills_PZ(character, 15)
        character:die()
    end
end

-- ------------------------------------------------------------

-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
-- Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)